name: avreen_bank
description: "AvreenBank Application."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=3.13.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter

  u:
    path: u_flutter

  flutter_native_splash: ^2.4.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  image_path: lib/assets/images/logo_launcher.png
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true

flutter_native_splash:
  color: "#F5F5F5"
  color_dark: "#000000"

  image: lib/assets/images/logo_launcher.png
  image_dark: lib/assets/images/logo_launcher.png

  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

  fullscreen: true
  android_min_sdk: 23

  android_12:
    color: "#F5F5F5"
    color_dark: "#000000"
    image: lib/assets/images/logo_launcher.png
    image_dark: lib/assets/images/logo_launcher.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#111111"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/banks/
