name: avreen_bank
description: "AvreenBank Application."
publish_to: 'none'
version: 0.1.0+10

environment:
  sdk: ">=3.13.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter

  u:
    path: U_flutter

  flutter_native_splash: ^2.4.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  image_path: lib/assets/images/logo_launcher.jpeg
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true

flutter_native_splash:
  color: "#ffffff"
  image: lib/assets/images/logo_launcher.jpeg
  branding: lib/assets/images/please_wait.png
  color_dark: "#ffffff"
  image_dark: lib/assets/images/logo_launcher.jpeg
  branding_dark: lib/assets/images/please_wait.png

#  android_gravity: center
#  ios_content_mode: center
#  web_image_mode: center

#  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/banks/
